language: rust

script:
- bundle install
- bundle exec jekyll build
- cargo run --manifest-path tools/fix-base-url/Cargo.toml -- _site

before_deploy:
- nvm use stable
- npm install -g ipfs-deploy

deploy:
  provider: script
  skip_cleanup: true
  script: ipd -OC -p pinata -d cloudflare
  'on':
    branch: master
